name: pulsenest_tracker
description: "PulseNest helps you track workouts, meals, and body measurements in one place."
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  file_selector: ^1.0.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
